import{a as L,S as w,i as s}from"./assets/vendor-D73Uttp0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(r){if(r.ep)return;r.ep=!0;const a=t(r);fetch(r.href,a)}})();const S="46880481-b4b8ce5da8d344b0e4ba41140",v="https://pixabay.com/api/";async function u(e,o=1){const t=new URLSearchParams({key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o});try{return(await L.get(`${v}?${t}`)).data}catch{throw new Error("Failed to fetch images")}}function f(e){return`
    <div class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">  
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" loading="lazy"/>
        <div class="image-info">
          <p class="info"><b>Likes</b> ${e.likes}</p>
          <p class="info"><b>Views</b> ${e.views}</p>
          <p class="info"><b>Comments</b> ${e.comments}</p>
          <p class="info"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </a>
    </div>
  `}function m(){const e=document.querySelector("#load-more");e&&(e.style.display="block")}function y(){const e=document.querySelector("#load-more");e&&(e.style.display="none")}function h(){const e=document.querySelector(".loader");e&&(e.style.display="block")}function p(){const e=document.querySelector(".loader");e&&(e.style.display="none")}const q=document.querySelector(".input-container"),P=document.querySelector(".input"),l=document.querySelector(".gallery"),E=document.querySelector("#load-more");let i=1,g="",d=0;const b=new w(".gallery a",{captionsData:"alt",captionDelay:250});async function M(e){e.preventDefault();const o=P.value.trim();if(o===""){s.error({title:"Error",message:"Please enter search query"});return}i=1,g=o,l.innerHTML="",y(),h();try{const t=await u(o,i);if(d=t.totalHits,t.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=t.hits.map(r=>f(r)).join("");l.innerHTML=n,b.refresh(),t.hits.length<d&&m()}catch(t){s.error({title:"Error",message:"An error occurred while fetching images. Please try again later!"}),console.error(t)}finally{p()}}async function B(){i+=1,y(),h();try{const o=(await u(g,i)).hits.map(r=>f(r)).join("");l.insertAdjacentHTML("beforeend",o),b.refresh();const{height:t}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),i*15>=d?s.info({message:"We're sorry, but you've reached the end of search results."}):m()}catch(e){s.error({title:"Error",message:"An error occurred while loading more images. Please try again later!"}),console.error(e)}finally{p()}}q.addEventListener("submit",M);E.addEventListener("click",B);
//# sourceMappingURL=index.js.map
